UXES.C.APP_ID               = UXES.VALUE_NOT_INITIALIZED;
UXES.C.APP_NAME             = UXES.VALUE_NOT_INITIALIZED;
UXES.C.DIRNAME_PREFERENCES  = UXES.VALUE_NOT_INITIALIZED;
UXES.C.FILENAME_PREFERENCES = UXES.VALUE_NOT_INITIALIZED;
