//@targetengine UXES.extendScriptEngine

// Generated by UXPScriptSparker
// https://github.com/zwettemaan/UXPScriptSparker

// Generic launcher. Running this script will run the script in InDesignBrot.js 
// in the ExtendScript environment

if ("undefined" == typeof UXES) {
    UXES = {};
}

//@include "InDesignBrot_helpers/jsx/runtime.jsx"
UXES.loadModules(UXES);

