//@targetengine UXES.extendScriptEngine

// Generated by UXPScriptSparker
// https://github.com/zwettemaan/UXPScriptSparker

//
// Do not run this code directly. 
// Instead, this code can be launched either in ExtendScript or in UXPScript,
// by running either the run...jsx or the run...idjs 
// scripts from the Scripts Panel
//


// Generic launcher. Running this script will run the script in InDesignBrot.js 
// in the ExtendScript environment

if ("undefined" == typeof UXES) {
    UXES = {};
}

//@include "InDesignBrot_helpers/jsx/runtime.jsx"
UXES.loadModules(UXES);
